### ISSUE TITLE
Support for typescript

### ISSUE THREAD

**Issue by axelson** [codemix/deprank#4]
Is typescript intended to be supported? deprank is only printing out the header and doesn't seem to find any typescript files.

Here's the deprank command that I am running:

```
npx deprank js/ --ext ".ts,.tsx"
| Filename | Lines | Dependents | PageRank |
--------------------------------------------
```

But the following dependency cruiser command works fine and creates a svg with the files that I expect:
```
depcruise --include-only "^js" --output-type dot js | dot -T svg > dependencygraph.svg
```

**Comment by phpnode** [comment]
this is a quirk of how dependency cruiser works - you need to have typescript reachable via a nearby `node_modules`, see https://github.com/sverweij/dependency-cruiser/blob/develop/doc/faq.md#features

If it's still not working, I'd suggest installing deprank as a dependency of your project, or globally like dependency cruiser, rather than running it via npx
